apiVersion: apps/v1
kind: Deployment
metadata:
  name: rick-morty-app
  labels:
    app: rick-morty
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: rick-morty #d
  template:
    metadata:
      labels:
        app: rick-morty
    spec:
      containers:
      - name: rick-morty-container
        image: rick-morty-app:latest 
        imagePullPolicy: Never # k8s know to use with local image
        ports:
        - containerPort: 5000 
        

        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10